name: generate fonts

on:
  push:
    tags:
      - 'v*.*.*'

concurrency: generate-fonts

jobs:
  prepare:
    if: github.repository == 'jonz94/Sarasa-Gothic-Nerd-Fonts'
    runs-on: ubuntu-latest
    env:
      NERD_FONTS_VERSION: v2.1.0
    steps:
      - uses: actions/checkout@v2
      - name: download font patcher
        run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/${NERD_FONTS_VERSION}/font-patcher --output font-patcher
      - name: download source glyphs
        run: bash download-source-glyphs.sh
      - run: tree .
      - name: upload font patcher and source glyphs
        uses: actions/upload-artifact@v2
        with:
          name: font patcher and source glyphs
          path: |
            font-patcher
            src/glyphs/*

  patch1:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        styles: ['fixed', 'fixed-slab', 'mono', 'mono-slab']
        orthographies: ['cl', 'hc', 'j', 'k', 'sc', 'tc']
        variants:
          [
            'regular',
            'italic',
            'bold',
            'bolditalic',
            'semibold',
            'semibolditalic',
            'light',
            'lightitalic',
            'extralight',
            'extralightitalic',
          ]
    env:
      FILENAME: 'sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}'
    steps:
      - uses: actions/checkout@v2
      - name: Download latest version of Sarasa Gothic from GitHub release page
        run: |
          LATEST_TAG=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          echo downloading Sarasa Gothic ${LATEST_TAG}
          curl --retry 3 --retry-delay 5 -L https://github.com/be5invis/Sarasa-Gothic/releases/download/${LATEST_TAG}/sarasa-gothic-ttf-${LATEST_TAG:1}.7z -o sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - name: install FontForge
        run: sudo apt install fontforge -y
      - name: download font patcher and source glyphs
        uses: actions/download-artifact@v2
        with:
          name: font patcher and source glyphs
      - run: tree .
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install configparser
        run: pip install configparser
      - run: ls -l
      - name: patch font
        run: fontforge -script font-patcher --adjust-line-height --careful --complete --no-progressbars --quiet "${FILENAME}.ttf"
      - run: ls -l
      - name: rename patched font files
        run: mv *Complete.ttf "${FILENAME}-nerd-font.ttf"
      - run: ls -l
      - name: install fonttools
        run: pip install fonttools
      - name: correcting xAvgCharWidth to fix alignment issue
        run: |
          ttx -t "OS/2" "${FILENAME}.ttf"
          ttx -t "OS/2" "${FILENAME}-nerd-font.ttf"
          ls -l *.ttx
          cat "${FILENAME}.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          original_x_avg_char_width="$(grep xAvgCharWidth "${FILENAME}.ttx" | cut -d '"' -f 2)"
          echo original xAvgCharWidth is $original_x_avg_char_width
          sed -i "s/xAvgCharWidth value=\"[0-9]\+\"/xAvgCharWidth value=\"${original_x_avg_char_width}\"/g" "${FILENAME}-nerd-font.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          mv "${FILENAME}-nerd-font.ttf" "${FILENAME}-nerd-font.original.ttf"
          ttx -o "${FILENAME}-nerd-font.ttf" -m "${FILENAME}-nerd-font.original.ttf" "${FILENAME}-nerd-font.ttx"
      - name: build hdmx table to fix alignment issue
        run: python build-hdmx-for-sarasa.py "${FILENAME}-nerd-font.ttf"
      - name: correct TTF font family name
        run: python correct-ttf-font-family-name.py "${FILENAME}-nerd-font.ttf"
      - name: upload patched font
        uses: actions/upload-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }} font
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf

  patch2:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        styles: ['term', 'term-slab', 'gothic', 'ui']
        orthographies: ['cl', 'hc', 'j', 'k', 'sc', 'tc']
        variants:
          [
            'regular',
            'italic',
            'bold',
            'bolditalic',
            'semibold',
            'semibolditalic',
            'light',
            'lightitalic',
            'extralight',
            'extralightitalic',
          ]
    env:
      FILENAME: 'sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}'
    steps:
      - uses: actions/checkout@v2
      - name: download latest version of Sarasa Gothic from GitHub release page
        run: |
          LATEST_TAG=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          echo downloading Sarasa Gothic ${LATEST_TAG}
          curl --retry 3 --retry-delay 5 -L https://github.com/be5invis/Sarasa-Gothic/releases/download/${LATEST_TAG}/sarasa-gothic-ttf-${LATEST_TAG:1}.7z -o sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - name: install FontForge
        run: sudo apt install fontforge -y
      - name: download font patcher and source glyphs
        uses: actions/download-artifact@v2
        with:
          name: font patcher and source glyphs
      - run: tree .
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install configparser
        run: pip install configparser
      - run: ls -l
      - name: patch font
        run: fontforge -script font-patcher --adjust-line-height --careful --complete --no-progressbars --quiet "${FILENAME}.ttf"
      - run: ls -l
      - name: rename patched font files
        run: mv *Complete.ttf "${FILENAME}-nerd-font.ttf"
      - run: ls -l
      - name: install fonttools
        run: pip install fonttools
      - name: correcting xAvgCharWidth to fix alignment issue
        run: |
          ttx -t "OS/2" "${FILENAME}.ttf"
          ttx -t "OS/2" "${FILENAME}-nerd-font.ttf"
          ls -l *.ttx
          cat "${FILENAME}.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          original_x_avg_char_width="$(grep xAvgCharWidth "${FILENAME}.ttx" | cut -d '"' -f 2)"
          echo original xAvgCharWidth is $original_x_avg_char_width
          sed -i "s/xAvgCharWidth value=\"[0-9]\+\"/xAvgCharWidth value=\"${original_x_avg_char_width}\"/g" "${FILENAME}-nerd-font.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          mv "${FILENAME}-nerd-font.ttf" "${FILENAME}-nerd-font.original.ttf"
          ttx -o "${FILENAME}-nerd-font.ttf" -m "${FILENAME}-nerd-font.original.ttf" "${FILENAME}-nerd-font.ttx"
      - name: build hdmx table to fix alignment issue
        run: python build-hdmx-for-sarasa.py "${FILENAME}-nerd-font.ttf"
      - name: correct TTF font family name
        run: python correct-ttf-font-family-name.py "${FILENAME}-nerd-font.ttf"
      - name: Upload patched font
        uses: actions/upload-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }} font
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf

  zip:
    needs: [patch1, patch2]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        styles: ['fixed', 'fixed-slab', 'mono', 'mono-slab', 'term', 'term-slab', 'gothic', 'ui']
        orthographies: ['cl', 'hc', 'j', 'k', 'sc', 'tc']
    steps:
      # start of part generated by `generate-download-patched-fonts` script
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-regular font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-italic font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bold font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bolditalic font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibold font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibolditalic font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-light font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-lightitalic font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralight font
      - uses: actions/download-artifact@v2
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralightitalic font
      # end of part generated by `generate-download-patched-fonts` script

      - run: ls -l
      - name: zip patched font files
        run: zip -r sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-*-nerd-font.ttf
      - run: ls -l
      - name: upload zip
        uses: actions/upload-artifact@v2
        with:
          name: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip

  release:
    needs: zip
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - run: ls -l

      # start of part generated by `generate-download-patched-zips` script
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-tc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-slab-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-slab-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-fixed-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-tc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-slab-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-slab-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-mono-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-tc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-slab-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-slab-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-term-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-gothic-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-gothic-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-gothic-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-gothic-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-gothic-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-gothic-tc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-ui-cl-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-ui-hc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-ui-j-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-ui-k-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-ui-sc-nerd-font.zip
      - uses: actions/download-artifact@v2
        with:
          name: sarasa-ui-tc-nerd-font.zip
      # end of part generated by `generate-download-patched-zips` script

      - run: ls -l
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
